InstaMvc/InstaMvc/Controllers/PostController.cs
using InstaMvc.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InstaMvc
{
    [Authorize]

    public class PostController : Controller
    {
        private long? _currentUserId { get { return ((CustomAuth.CustomPrincipal)User)?.UserId; } }
        // GET: Post
        public ActionResult Index()
        {
            var model = new Models.PostsModel { FormMode = PostFormMode.all };
            model.Posts = BLL.Data.GetPosts();

            model.NextExist = BLL.Data.GetPosts(1).Any();

            return View(model);
        }
        public ActionResult My()
        {
            var model = new Models.PostsModel { FormMode = PostFormMode.my };
            model.Posts = BLL.Data.GetPosts(userId: _currentUserId);
            model.NextExist = BLL.Data.GetPosts(1, _currentUserId).Any();
            return View("Index", model);
        }

        [HttpPost]
        public JsonResult PublishPost(long id)
        {
            var result = new JsonResultResponse { Success = true };
            try
            {
                BLL.Data.PublishPost(id);
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.Result = ex.Message;
            }
            return Json(result);

        }

        [HttpGet]
        public PartialViewResult Create()
        {
            ViewBag.Images = BLL.Data.GetMyImagesIds(_currentUserId.Value);



            return PartialView();
        }
        [HttpPost]
        public JsonResult Create(BLL.DTO.PostDTO model)
        {
            var result = new JsonResultResponse { Success = true };
            try
            {
                model.UserId = _currentUserId.Value;

                BLL.Data.CreatePost(model);
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.Result = ex.Message;
            }
            return Json(result);
        }




        [HttpPost]
        public JsonResult UploadImages()
        {
            var result = new JsonResultResponse { Success = true };
            try
            {
                if (Request.Files != null && Request.Files.Count != 0 && Request.Files[0].ContentLength > 0)
                {
                    var file = Request.Files[0];

                    var userId = _currentUserId.Value;

                    result.Result = BLL.Data.AddImage(userId, new BLL.DTO.ImageWrapper(file));
                }
                else
                    throw new Exception("Не найдено файлов");

            }
            catch (Exception ex)
            {
                result.Success = false;
                result.Result = ex.Message;
            }
            return Json(result);

        }

        public ActionResult GetImage(long Id)
        {
            var avatar = BLL.Data.GetImage(Id);

            if (avatar.Content == null)
                return HttpNotFound();

            return File(avatar.Content, avatar.Mime);
        }

        [HttpPost]
        public JsonResult DelImage(long id)
        {
            var result = new JsonResultResponse { Success = true };
            try
            {
                BLL.Data.DelImage(id);
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.Result = ex.Message;
            }
            return Json(result);

        }

        public PartialViewResult GetPosts(int page, bool my = false)
        {
            var model = new Models.PostsModel { FormMode = my ? PostFormMode.my : PostFormMode.all };
            model.Posts = BLL.Data.GetPosts(page, my ? _currentUserId : null);
            model.NextExist = BLL.Data.GetPosts(page + 1, my ? _currentUserId : null).Any();

            return PartialView("_MorePostsView", model);
        }

        public PartialViewResult GetPost(long id)
        {
            var model = BLL.Data.GetPostById(id);
            return PartialView("_PostView", model);
        }

        public JsonResult GetComments(long id)
        {
            var model = BLL.Data.GetPostById(id);
            return Json(new { model.Comments },JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult AddComment(long postId, string commentText)
        {
            var result = new JsonResultResponse { Success = true };
            try
            {
                var userId = _currentUserId.Value;

                var comId = BLL.Data.CreateComment(new BLL.DTO.CommentDTO { UserId = userId, CommentText = commentText, PostId = postId, Date = DateTime.Now });


                result.Result = BLL.Data.GetComment(comId);

            }
            catch (Exception ex)
            {
                result.Success = false;
                result.Result = ex.Message;
            }
            return Json(result);
        }

    }
}

InstaMvc/InstaMvc/Controllers/UserController.cs
using InstaMvc.CustomAuth;
using InstaMvc.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace InstaMvc.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Registration()
        {
            var model = new Models.RegistrationModel()
            { SharedProfile = true };

            return View(model);
        }

        [HttpPost]
        public ActionResult Registration(Models.RegistrationModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            try
            {
                var salt = BLL.Hash.CreateSalt(16);
                var passhash = BLL.Hash.GenerateSaltedHash(model.Password, salt);
                var res = BLL.Data.CreateUpdateUser(new BLL.DTO.UserDTO
                {
                    Salt = Convert.ToBase64String(salt),
                    PasswordHash = Convert.ToBase64String(passhash),
                    Nickname = model.Nickname,
                    Birtdate = model.Birtdate,
                    RegDate = DateTime.Now,
                    SharedProfile = model.SharedProfile,
                    LoginName = model.LoginName
                });
                ViewBag.Message = res;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }


            return View(model);
        }

        [HttpGet]
        public ActionResult Login(string ReturnUrl = "")
        {
            if (User.Identity.IsAuthenticated)
            {
                return LogOut();
            }
            ViewBag.ReturnUrl = ReturnUrl;
            return View();
        }

        [HttpPost]
        public ActionResult Login(Models.LoginModel model, string ReturnUrl = "")
        {

            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(model.Login, model.Password))
                {
                    var user = (CustomMembershipUser)Membership.GetUser(model.Login, false);
                    if (user != null)
                    {
                        CustomSerializeModel userModel = new Models.CustomSerializeModel()
                        {
                            UserId = user.UserId,
                            Nickname = user.Nickname,
                            Email = user.Email,
                        };

                        string userData = JsonConvert.SerializeObject(userModel);
                        FormsAuthenticationTicket authTicket = new FormsAuthenticationTicket
                            (
                            1, model.Login, DateTime.Now, DateTime.Now.AddMinutes(15), false, userData
                            );

                        string enTicket = FormsAuthentication.Encrypt(authTicket);
                        HttpCookie faCookie = new HttpCookie("Cookie1", enTicket);
                        Response.Cookies.Add(faCookie);
                    }

                    if (Url.IsLocalUrl(ReturnUrl))
                    {
                        return Redirect(ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            ModelState.AddModelError("", "Something Wrong : Username or Password invalid ^_^ ");
            return View(model);

        }
        public ActionResult LogOut()
        {
            HttpCookie cookie = new HttpCookie("Cookie1", "");
            cookie.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie);

            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult AccessDenied()
        {
            return View();
        }


    }
}

InstaMvc/InstaMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/preloader.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="http://twitter.github.com/hogan.js/builds/3.0.1/hogan-3.0.1.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.preloader.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Posts", "Index", "Post", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>


    <div id="header_container">
        <div id="header">
           
            <span style="float:right; font-size:small">
                @if (HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    var identity = ((InstaMvc.CustomAuth.CustomPrincipal)HttpContext.Current.User);
                    @Html.Label(string.Format("Welcome {0}", identity.Nickname))
                    @Html.ActionLink("Log out", "LogOut", "User")
                }
                else
                {
                    @Html.ActionLink("Login", "Login", "User")
                }
            </span>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

</body>
<script>
    var Loader = {
        show: function () {
            $('body').preloader();
        },
        hide: function () {
            $('body').preloader('remove');
        }
    };
</script>
</html>